/** Suggested car features for admin fleet form — grouped for quick selection */
export const CAR_FEATURE_GROUPS: { label: string; features: string[] }[] = [
  {
    label: 'Climate & Comfort',
    features: [
      'Air Conditioning (AC)',
      'Climate Control',
      'Dual Zone AC',
      'Heated Seats',
      'Ventilated Seats',
      'Leather Upholstery',
      'Power Adjustable Seats',
      'Rear AC Vents',
      'Cooled Glove Box',
    ],
  },
  {
    label: 'Audio & Connectivity',
    features: [
      'Bluetooth',
      'Apple CarPlay',
      'Android Auto',
      'Premium Audio System',
      'Touchscreen Infotainment',
      'Wireless Charging',
      'USB Ports',
      'Aux Input',
      'Voice Commands',
      'Rear Entertainment Screens',
    ],
  },
  {
    label: 'Safety & Driver Assist',
    features: [
      'ABS',
      'Airbags',
      'ESP / Traction Control',
      'Rear Parking Camera',
      '360° Camera',
      'Parking Sensors',
      'Blind Spot Monitor',
      'Lane Departure Warning',
      'Adaptive Cruise Control',
      'Automatic Emergency Braking',
      'Hill Hold Assist',
      'ISOFIX Child Seat Mounts',
    ],
  },
  {
    label: 'Exterior & Lighting',
    features: [
      'Sunroof',
      'Panoramic Sunroof',
      'Alloy Wheels',
      'LED Headlights',
      'DRL (Daytime Running Lights)',
      'Fog Lamps',
      'Rain Sensing Wipers',
      'Roof Rails',
      'Chrome Accents',
      'Spoiler',
    ],
  },
  {
    label: 'Convenience',
    features: [
      'Keyless Entry',
      'Push Button Start',
      'Remote Start',
      'GPS Navigation',
      'Cruise Control',
      'Auto Headlamps',
      'Power Windows',
      'Power ORVMs',
      'Foldable Rear Seats',
      'Split Folding Seats',
      'Boot Space Light',
      'Tyre Pressure Monitor',
    ],
  },
  {
    label: 'Performance & Drive',
    features: [
      'Turbocharged Engine',
      'All-Wheel Drive (AWD)',
      '4WD',
      'Sport Mode',
      'Eco Mode',
      'Paddle Shifters',
      'Drive Mode Selector',
      'Regenerative Braking',
      'Fast Charging (EV)',
    ],
  },
];

export const ALL_SUGGESTED_FEATURES = CAR_FEATURE_GROUPS.flatMap(g => g.features);
